export const EventEditActionTypes = {
  EDIT_PAGE_OPEN_SUCCESS: 'EDIT_PAGE_OPEN_SUCCESS',
  EDIT_PAGE_OPEN_FAILED: 'EDIT_PAGE_OPEN_SUCCESS',
  EDIT_PAGE_CLOSE_SUCCESS: 'EDIT_PAGE_CLOSE_SUCCESS',
  EDIT_PAGE_CLOSE_FAILED: 'EDIT_PAGE_CLOSE_FAILED'
}