export const BodyScrollType = {
  SAVE_BODY_SCROLL_SUCCESS: 'SAVE_BODY_SCROLL_SUCCESS',
  SAVE_BODY_SCROLL_FAILED: 'SAVE_BODY_SCROLL_FAILED',
  SET_BODY_SCROLL_SUCCESS: 'SET_BODY_SCROLL_SUCCESS',
  SET_BODY_SCROLL_FAILED: 'SET_BODY_SCROLL_FAILED',
  RESET_BODY_SCROLL: 'RESET_BODY_SCROLL',
}