export const UserActionTypes = {
  USER_LOADING: 'USER_LOADING',
  USER_NOT_LOADING: 'USER_NOT_LOADING', 
  SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_FAILED: 'SET_CURRENT_USER_FAILED',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILED: 'SIGNIN_FAILED',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILED: 'SIGNOUT_FAILED',
  EDIT_SUCCESS: 'EDIT_SUCCESS',
  EDIT_FAILED: 'EDIT_FAILED',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  DELETE_FAILED: 'DELETE_FAILED'
};