export const EventsActionTypes = {
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_FAILED: 'FETCH_EVENTS_FAILED',
  SET_EVENT_GUEST_SUCCESS: 'SET_EVENT_GUEST_SUCCESS',
  SET_EVENT_GUEST_FAILED: 'SET_EVENT_GUEST_FAILED',
  DELETE_EVENT_GUEST_SUCCESS: 'DELETE_EVENT_GUEST_SUCCESS',
  DELETE_EVENT_GUEST_FAILED: 'DELETE_EVENT_GUEST_FAILED',
};