export const EventsActionTypes = {
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_FAILED: 'FETCH_EVENTS_FAILED',
  SET_EVENT_GUEST_SUCCESS: 'SET_EVENT_GUEST_SUCCESS',
  SET_EVENT_GUEST_FAILED: 'SET_EVENT_GUEST_FAILED',
  DELETE_EVENT_GUEST_SUCCESS: 'DELETE_EVENT_GUEST_SUCCESS',
  DELETE_EVENT_GUEST_FAILED: 'DELETE_EVENT_GUEST_FAILED',
  CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
  CREATE_EVENT_FAILED: 'CREATE_EVENT_FAILED',
  EDIT_EVENT_SUCCESS: 'EDIT_EVENT_SUCCESS',
  EDIT_EVENT_FAILED: 'EDIT_EVENT_FAILED',
  DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_FAILED: 'DELETE_EVENT_FAILED',
  SET_FILTER_TYPE: 'SET_FILTER_TYPE'
};